# Generated by Django 4.1 on 2024-04-05 05:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialdata',
            name='name',
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='palika_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
