# Generated by Django 4.1 on 2024-04-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geospatial', '0002_remove_geospatialdata_name_geospatialdata_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialdata',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='geospatialdata/'),
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
