# Generated by Django 4.1 on 2024-04-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0004_palikaupload_palikageometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palikageometry',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='palikageometry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='palikageometry',
            name='username',
        ),
        migrations.AddField(
            model_name='palikageometry',
            name='palikaupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geospatial.palikaupload'),
        ),
    ]
