# Generated by Django 4.1 on 2024-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0005_remove_palikageometry_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
