# Generated by Django 4.1 on 2024-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0008_alter_palikageometry_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palikageometry',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
