# Generated by Django 4.1 on 2024-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0011_palikageometry_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='bbox_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
