# Generated by Django 4.1 on 2024-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0012_palikageometry_bbox_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='bbox',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
