# Generated by Django 4.1 on 2024-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0014_palikageometry_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='extra_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
