# Generated by Django 4.1 on 2024-04-09 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geospatial', '0016_rename_state_palikageometry_ward_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('healthcare', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
