# Generated by Django 4.1 on 2024-04-09 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0017_jsongeometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsongeometry',
            old_name='amenity',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='jsongeometry',
            old_name='healthcare',
            new_name='palika_name',
        ),
        migrations.RenameField(
            model_name='jsongeometry',
            old_name='name_en',
            new_name='ward_number',
        ),
        migrations.RemoveField(
            model_name='jsongeometry',
            name='name_ne',
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='bbox',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='bbox_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='extra_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='file_type',
            field=models.CharField(blank=True, choices=[('shapefile', 'Shapefile'), ('geojson', 'GeoJSON')], default='shapefile', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='palikaupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geospatial.palikaupload'),
        ),
        migrations.AddField(
            model_name='jsongeometry',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
