# Generated by Django 4.1 on 2024-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0018_rename_amenity_jsongeometry_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsongeometry',
            name='file_type',
            field=models.CharField(blank=True, choices=[('shapefile', 'Shapefile'), ('geojson', 'GeoJSON')], default='geojson', max_length=100, null=True),
        ),
    ]
