# Generated by Django 4.1 on 2024-04-10 10:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geospatial', '0019_alter_jsongeometry_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('amenity', models.CharField(blank=True, max_length=100, null=True)),
                ('wheelchair', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
