# Generated by Django 4.1 on 2024-04-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0021_remove_bankgeometry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankgeometry',
            name='palikaupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geospatial.palikaupload'),
        ),
    ]
