# Generated by Django 4.1 on 2024-04-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0022_bankgeometry_palikaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankgeometry',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='geospatialdata'),
        ),
        migrations.AlterField(
            model_name='palikaupload',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='geospatialdata'),
        ),
    ]
