# Generated by Django 4.1 on 2024-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0024_weatherforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
