version: "3"

services:
  web:
    env_file:
      - .env
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - task-network
    depends_on:
      - db
    entrypoint: ./entrypoint.sh

  db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    volumes:
      - ./postgis_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - task-network
    ports:
      - 5433:5432

networks:
  task-network:
    driver: bridge



            
