# Generated by Django 5.0.3 on 2024-03-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='is_created',
        ),
    ]
