# Generated by Django 5.0.3 on 2024-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_category_task_due_date_task_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0),
        ),
    ]
