# Generated by Django 5.0.3 on 2024-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study'), ('health', 'Health'), ('finance', 'Finance'), ('home', 'Home'), ('social', 'Social'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('n/a', 'N/A')], default='N/A', max_length=15),
        ),
    ]
