# Generated by Django 4.1 on 2024-04-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAuth',
            new_name='User',
        ),
    ]
