# Generated by Django 4.1 on 2024-04-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
